services:
  api:
    build: .
    container_name: realityzando-api
    restart: always
    environment:
      - NODE_ENV=production
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp=unconfined
    shm_size: '1gb'
    mem_limit: '2g'
    memswap_limit: '2g'
    ports:
      - "3000:3000"
    networks:
      - realityzando-network

networks:
  realityzando-network:
    external: true